// Generated by CoffeeScript 1.8.0
(function() {
  var commandWasIssued;

  commandWasIssued = function(event) {
    var activeTab, _ref;
    if (event.command === "minipostWasLaunched") {
      activeTab = event.target.browserWindow.activeTab;
      if ((_ref = activeTab.url) != null ? _ref.match("/write") : void 0) {
        return activeTab.url = location.toString().replace("safari.global", "unlock");
      } else {
        return activeTab.url = location.toString().replace("safari.global", "write");
      }
    }
  };

  safari.application.addEventListener("command", commandWasIssued, false);

}).call(this);
